### ISSUE TITLE
Proxy is running but browser not connect with grpc Server

### ISSUE THREAD

**Issue by hunnain** [grpc/grpc#16720]
Hi i have created envoy proxy. **Proxy is running on port 8080** when ever i call port from browser so its show me error **code 12** but cant show any message actually browser are not connecting with grpc server.**grpc server was running on port 9090** i have also given in envoy.yaml file but its not working
I am using reactjs so here my code to connect with grpc proxy which will connect me to grpc server
`const client = new TodoServiceClient('http://localhost:8080');`
as i given my proxy port is 8080 thats why i am calling that port from react but it given me code 12 sometimes gives me and cross origin erros.Cors is also enable.
**My react clientside is running on port 8081**.

This is my Docker file
`FROM envoyproxy/envoy:latest CMD /usr/local/bin/envoy -c ../../envoy.yaml -l trace --log-path /tmp/envoy_info.log`

My docker compose file

```
version: '3'
services:
  envoy:
    build:
      context: ./
      dockerfile: ./envoy/docker/Dockerfile
    image: grpcweb/envoy
    ports:
      - "8080:8080"
    links:
      - echo-server
```
My envoy.yaml file
```
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 8081 }

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 8081 }
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          codec_type: auto
          stat_prefix: ingress_http
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route: { cluster: echo_service }
              cors:
                allow_origin:
                - "*"
                allow_methods: GET, PUT, DELETE, POST, OPTIONS
                allow_headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web
                max_age: "1728000"
                expose_headers: custom-header-1,grpc-status,grpc-message
                enabled: true
          http_filters:
          - name: envoy.grpc_web
          - name: envoy.cors
          - name: envoy.router
  clusters:
  - name: echo_service
    connect_timeout: 0.25s
    type: logical_dns
    http2_protocol_options: {}
    lb_policy: round_robin
    hosts: [{ socket_address: { address: 0.0.0.0, port_value: 9090 }}]
```
My client side React code
```
const client = new TodoServiceClient('http://localhost:8080');
  var request = new Todo();
  request.setTodo('My todo');
  // request.setDescription("My description")
  var metadata = {'custom-header-1': 'value1'};
  var call = client.insert(request, metadata, function(err, response) {
    if (err) {
      console.log("My error",err.code);
      console.log("My error message",err.messge);
    } else {
      console.log(response.getMessage());
    }
  });
```
![screenshot from 2018-09-26 13-06-31](https://user-images.githubusercontent.com/24963356/46158415-3b90dd80-c297-11e8-8948-e1851a8fdca0.png)

Please guide me what i am doing wrong i have also running docker i run proxy server using docker-compose up -d envoy everything is running fine but when i call proxy from browser because proxy is the main way to connect with gRPC server.Its how me error code 12
This issue will help everyone whose working on react and other library of web so please help me there is no tutorial of this.
Thanks.
