### ISSUE TITLE
"grpc_message":"Stream removed","grpc_status":2

### ISSUE THREAD

**Issue by ak-em1603** [grpc/grpc#31581]
I am running a python grpc server and using envoy to connect to it through client. The envoy is deployed in GKE. I am attaching the envoy deployment yaml.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy-deployment
  labels:
    app: envoy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envoy
  template:
    metadata:
      labels:
        app: envoy
    spec:
      containers:
      - name: envoy
        image: envoyproxy/envoy:v1.22.5
        ports:
        - containerPort: 9901
        livenessProbe:
          httpGet:
            path: /healthz
            port: 9901
          initialDelaySeconds: 60
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 2
        readinessProbe:
          httpGet:
            path: /healthz
            port: 9901
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 10
          failureThreshold: 2
        volumeMounts:
        - name: config
          mountPath: /etc/envoy
      volumes:
      - name: config
        configMap:
          name: envoy-conf
---
apiVersion: v1
kind: Service
metadata:
  name: envoy-deployment-service
  annotations:
    cloud.google.com/backend-config: '{"ports": {"9903":"envoy-app-backend-config"}}'
spec:
  ports:
  - protocol: TCP
    port: 9903
    targetPort: 9901
  selector:
    app: envoy
  type: LoadBalancer
  externalTrafficPolicy: Local
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: envoy-app-backend-config
spec:
  customRequestHeaders:
    headers:
    - "TE:trailers"
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: envoy-ingress-prod
  namespace: seshat
  annotations:
    kubernetes.io/ingress.global-static-ip-name: envoy-ingress
    kubernetes.io/ingress.allow-http: "false"
    cert-manager.io/issuer: superset-issuer
    cloud.google.com/backend-config: '{"default": "envoy-app-backend-config"}'

  labels:
    name: envoy-ingress-app
spec:
  tls:
  - hosts:
    - example.com
    secretName: example-tls
  rules:
  - host: example.com
    http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: envoy-deployment-service
            port:
              number: 9903
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-conf

data:
  envoy.yaml: |
    admin:
      access_log_path: /tmp/admin_access.log
      address:
        socket_address: { address: 127.0.0.1, port_value: 9902 }

    static_resources:
      listeners:
        - name: listener_0
          address:
            socket_address: { address:  0.0.0.0, port_value: 9901 }
          filter_chains:
            - filters:
              - name: envoy.filters.network.http_connection_manager
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                  codec_type: auto
                  access_log:
                  - name: envoy.access_loggers.file
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                      path: "/dev/stdout"
                      typed_json_format:
                        "@timestamp": "%START_TIME%"
                        client.address: "%DOWNSTREAM_REMOTE_ADDRESS%"
                        client.local.address: "%DOWNSTREAM_LOCAL_ADDRESS%"
                        envoy.route.name: "%ROUTE_NAME%"
                        envoy.upstream.cluster: "%UPSTREAM_CLUSTER%"
                        host.hostname: "%HOSTNAME%"
                        http.request.body.bytes: "%BYTES_RECEIVED%"
                        http.request.duration: "%DURATION%"
                        http.request.headers.bytes: "%REQUEST_HEADERS_BYTES%"
                        http.request.headers.accept: "%REQ(ACCEPT)%"
                        http.request.headers.authority: "%REQ(:AUTHORITY)%"
                        http.request.headers.te: "%REQ(:TE)%"
                        http.request.headers.id: "%REQ(X-REQUEST-ID)%"
                        http.request.headers.x_forwarded_for: "%REQ(X-FORWARDED-FOR)%"
                        http.request.headers.x_forwarded_proto: "%REQ(X-FORWARDED-PROTO)%"
                        http.request.headers.x_b3_traceid: "%REQ(X-B3-TRACEID)%"
                        http.request.headers.x_b3_parentspanid: "%REQ(X-B3-PARENTSPANID)%"
                        http.request.headers.x_b3_spanid: "%REQ(X-B3-SPANID)%"
                        http.request.headers.x_b3_sampled: "%REQ(X-B3-SAMPLED)%"
                        http.request.method: "%REQ(:METHOD)%"
                        http.response.body.bytes: "%BYTES_SENT%"
                  stat_prefix: ingress_http
                  route_config:
                    name: local_route
                    virtual_hosts:
                      - name: envoy_service
                        domains: ["*"]
                        routes:
                        - match:
                           prefix: "/healthz"
                          direct_response: { status: 200, body: { inline_string: "ok it is working now" } }
                        - match:
                           prefix: "/heal"
                          direct_response: { status: 200, body: { inline_string: "ok heal is working now" } }
                        - match:
                           prefix: "/"
                           #headers:
                           #  - name: te
                           #    exact_match: "trailers"
                          route: {
                            prefix_rewrite: "/",
                            cluster: envoy_service
                          }
                        cors:
                          allow_origin_string_match:
                            - prefix: "*"
                          allow_methods: GET, PUT, DELETE, POST, OPTIONS
                          allow_headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout
                          max_age: "1728000"
                          expose_headers: custom-header-1,grpc-status,grpc-message
                  http_filters:
                    - name: envoy.filters.http.cors
                      typed_config:
                        "@type": type.googleapis.com/envoy.extensions.filters.http.cors.v3.Cors
                    - name: envoy.filters.http.grpc_web
                      typed_config:
                        "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_web.v3.GrpcWeb
                    - name: envoy.filters.http.router
                      typed_config:
                        "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
      clusters:
        - name: envoy_service
          connect_timeout: 0.25s
          type: strict_dns
          http2_protocol_options: {}
          lb_policy: round_robin
          load_assignment:
            cluster_name: envoy_service
            endpoints:
              - lb_endpoints:
                - endpoint:
                    address:
                      socket_address:
                        address: seshat-app-server-headless
                        port_value: 8000
```

I have a python grpc server which recieves a proto message and publishes it to a topic in pub/sub. My python grpc server is deployed on GKE and  looks like this:-

```
server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))
    master_pb2_grpc.add_EventBusOneofServiceServicer_to_server(
        EventBusServiceServicer(), server
    )
    server.add_insecure_port("0.0.0.0:8000")
    server.start()
    print("server started")

    def handle_sigterm(*_):
        print("Received shutdown signal")
        all_rpcs_done_event = server.stop(30)
        all_rpcs_done_event.wait(30)
        print("Shut down gracefully")

    signal(SIGTERM, handle_sigterm)
    server.wait_for_termination()
```
My grpc python client runs on local and looks like this:-
```

class ExampleServiceClient(object):
    def __init__(self):
        """Initializer.
           Creates a gRPC channel for connecting to the server.
           Adds the channel to the generated client stub.
        Arguments:
            None.

        Returns:
            None.
        """
       
        self.channel = grpc.secure_channel("domain name", grpc.ssl_channel_credentials(), options=(('grpc.enable_http_proxy', 0),))
        self.stub = master_pb2_grpc.EventBusOneofServiceStub(self.channel)

    def receiveEvent(self, request):
        """Gets a user.
        Arguments:
            name: The resource name of a user.

        Returns:
            None; outputs to the terminal.
        """

        try:
            print(request)
         
            response = self.stub.ReceiveOneofEvent(request)
            print("User fetched.")
            print(response)
        except grpc.RpcError as err:
            print(err)
            print(err.details())  # pylint: disable=no-member
            print("{}, {}".format(err.code().name, err.code().value))  #


if __name__ == "__main__":
    os.environ['GRPC_TRACE'] = 'all'
    os.environ['GRPC_VERBOSITY'] = 'DEBUG'
    if os.environ.get('https_proxy'):
        print("yes proxy present")
        del os.environ['https_proxy']
    if os.environ.get('http_proxy'):
        print("yes proxy present")
        del os.environ['http_proxy']

    for x in range(1,2):
        client = ExampleServiceClient()
        from google.protobuf.json_format import Parse, MessageToJson
        msg = master_pb2.ReceiveOneofEventRequest()
        msg.r.first_name = "a"
        msg.r.last_name = "b"
        msg.r.email = "c"
        client.receiveEvent(msg)
```
When I make calls using client, I always get the error:-

```
<_InactiveRpcError of RPC that terminated with:
    status = StatusCode.UNKNOWN
    details = "Stream removed"
    debug_error_string = "{"created":"@1667812262.198477000","description":"Error received from peer ipv4:IP:443","file":"src/core/lib/surface/call.cc","file_line":967,"grpc_message":"Stream removed","grpc_status":2}"
>
Stream removed
UNKNOWN, (2, 'unknown')
```

The thing is even with this exception being thrown, the server is able to process the grpc client request. The message is successfully pushed to pub/sub topic but instead of returning the desired repsonse it throws this error on client. What might be the reason for the same?

Other thing is when I hit the server using this piece of code I get the desired response:- 
```
import requests, sys
import os
from struct import pack
msg = master_pb2.ReceiveOneofEventRequest()
msg.r.first_name = "Ajit"
msg.r.last_name = "Kumar"
msg.r.email = "email_test"
HOST = os.getenv('CLIENT_PROXY', "https://domain.com")
HEADERS = {'content-type': 'application/grpc+proto',"te": "trailers" , 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36'}
data = msg.SerializeToString()
data = pack('!cI',b'\0', len(data)) + data
resp = requests.post(HOST + "/proto_dir.v1.EventBusOneofService/ReceiveOneofEvent", data=data, headers=HEADERS )
# print(resp.content)
responeof = master_pb2.ReceiveOneofEventResponse()
responeof.ParseFromString(resp.content[5:])
print(responeof.resp_oneof)
```
Now I wonder whether this is grpc library issue or issue with my GKE deployment. Please help. 

**Packages used:-** 

protoc - 3.20.1
protobuf==3.20.1 --no-binary=protobuf
grpcio-tools==1.48.2
grpcio ==1.47.0
OS = MAC Ventura

Attaching grpc debug logs for more clarity :-

[grpc_logs.txt](https://github.com/grpc/grpc/files/9962840/grpc_logs.txt)

**Comment by ak-em1603** [comment]
Adding few more details that I came across during debugging. In https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/_channel.py, the `_handle_event() `method throws error for batch operation `cygrpc.ReceiveStatusOnClientOperation(_EMPTY_FLAGS)`. 

<img width="789" alt="Screenshot 2022-11-09 at 6 16 19 PM" src="https://user-images.githubusercontent.com/101722789/200834116-71cc6764-8d0d-4289-b25d-f58e87c9f9ff.png">

The highlighted part  is where the error is being thrown. What exactly does this operation do?

**Comment by ak-em1603** [comment]
@yashykt @gnossen Any updates on this? We are kind of blocked due to this. A quick resolution is appreciated.

**Comment by ak-em1603** [comment]
The issue seems to be with reading trailing metadata. When I run the same setup on local **without ingress** i.e  `grpc_client => envoy => grpc_server`, I recieve the trailing metadata
 ```
I1110 21:40:58.296130000 8668193472 parsing.cc:557]                    parsing trailing_metadata
D1110 21:40:58.296135000 8668193472 hpack_parser.cc:1065]              HTTP:1:TRL:CLI: grpc-status: 0
```
But when the setup is `gprc_client => gce ingress => envoy => grpc_server`, the trailing metadata is not recieved. What might be the reason for same?

**Comment by yashykt** [comment]
Just took a look at this, as @ak-em1603 observed, I do not see trailing metadata being received in the original logs

**Comment by gnossen** [comment]
@ak-em1603 Can you please provide some more details on the "GCE ingress" in your stack? This seems to be the relevant detail since removing it resolves the issue.

**Comment by ak-em1603** [comment]
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: envoy-ingress-prod
  namespace: seshat
  annotations:
    kubernetes.io/ingress.global-static-ip-name: envoy-ingress
    kubernetes.io/ingress.allow-http: "false"
    cert-manager.io/issuer: superset-issuer
    cloud.google.com/backend-config: '{"default": "envoy-app-backend-config"}'

  labels:
    name: envoy-ingress-app
spec:
  tls:
  - hosts:
    - example.com
    secretName: example-tls
  rules:
  - host: example.com
    http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: envoy-deployment-service
            port:
              number: 9903
```
This is the yaml config for ingress. This ingress when deployed has following components:-  TLS, Load balancer, Target proxies, Forwarding rules, Backend services.

**Comment by gnossen** [comment]
Do you have an HTTP2 app-protocol annotation (e.g. `cloud.google.com/app-protocols: '{"my-port":"HTTP2"}'`). it might be that the GCE ingress is simply not using HTTP/2.

**Comment by ak-em1603** [comment]
I have changed my envoy config  to support http2 health check and deployment files to this:- 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy-deployment
  
  labels:
    app: envoy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envoy
  template:
    metadata:
      labels:
        app: envoy
    spec:
      containers:
      - name: envoy
        image: envoyproxy/envoy:v1.22.5
        ports:
        - containerPort: 9901
        readinessProbe:
          httpGet:
            port: 9901
            httpHeaders:
            - name: x-envoy-livenessprobe
              value: healthz
            path: /healthz
            scheme: HTTPS
        livenessProbe:
          httpGet:
            port: 9901
            httpHeaders:
              - name: x-envoy-livenessprobe
                value: healthz
            path: /healthz
            scheme: HTTPS
        volumeMounts:
        - name: config
          mountPath: /etc/envoy
        - name: certs
          mountPath: /etc/ssl/envoy
      volumes:
      - name: config
        configMap:
          name: envoy-conf
      - name: certs
        secret:
          secretName: secret-tls
---
apiVersion: v1
kind: Service
metadata:
  name: envoy-deployment-service
  
  annotations:
    cloud.google.com/backend-config: '{"ports": {"443":"envoy-app-backend-config"}}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  ports:
  - protocol: TCP
    port: 443
    targetPort: 9901
  selector:
    app: envoy
  type: NodePort
  externalTrafficPolicy: Local
#  loadBalancerIP: 35.225.129.124

---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: envoy-app-backend-config
  
spec:
  timeoutSec: 30
  connectionDraining:
      drainingTimeoutSec: 30
  healthCheck:
    checkIntervalSec: 5
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTP2
    requestPath: /healthz
    port: 9901
  customRequestHeaders:
    headers:
    - "TE:trailers"
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: envoy-ingress-prod
  
  annotations:
#    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: static-ip
    kubernetes.io/ingress.allow-http: "false"
    cert-manager.io/issuer: issuer
    cloud.google.com/backend-config: '{"default": "envoy-app-backend-config"}'
#    cert-manager.io/cluster-issuer: letsencrypt-staging
#    acme.cert-manager.io/http01-edit-in-place: "true"
  labels:
    name: envoy-ingress-app
spec:
  tls:
  - hosts:
    - domain.com
    secretName: secret-tls
  rules:
  - host: domain.com
    http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: envoy-deployment-service
            port:
              number: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-server
  
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        name: server
        image: gcr.io/project/image:latest
        command: ["python3" , "/var/app/api/main.py"]
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /secrets/gcloud-auth
          name: gcloud-auth
          readOnly: true
        ports:
        - containerPort: 8000
      volumes:
      - name: gcloud-auth
        secret:
          secretName: gcloud
---
apiVersion: v1
kind: Service
metadata:
  name: app-server-headless
  
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: server
  ports:
    - name: grpc
      port: 8000
      targetPort: 8000
      protocol: TCP
```

My envoy_config is --

apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-conf
data:
  envoy.yaml: |
    admin:
      access_log_path: /tmp/admin_access.log
      address:
        socket_address: { address: 127.0.0.1, port_value: 9902 }

    static_resources:
      listeners:
        - name: listener_0
          address:
            socket_address: { address:  0.0.0.0, port_value: 9901 }
          filter_chains:
            - filters:
              - name: envoy.filters.network.http_connection_manager
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                  codec_type: auto
                  access_log:
                  - name: envoy.access_loggers.file
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                      path: "/dev/stdout"
                  stat_prefix: ingress_https
                  route_config:
                    name: local_route
                    virtual_hosts:
                      - name: envoy_service
                        domains: ["*"]
                        routes:
                        #- match:
                        #   prefix: "/healthz"
                        #  direct_response: { status: 200, body: { inline_string: "ok it is working now" } }
                        - match:
                           prefix: "/heal"
                          direct_response: { status: 200, body: { inline_string: "ok heal is working now" } }
                        
                        - match:
                            prefix: "/envoy/"
                          route: {
                            prefix_rewrite: "/",
                            cluster: envoy_service
                          }
    
                        - match:
                            prefix: "/"
                          route: {
                            prefix_rewrite: "/",
                            cluster: envoy_service
                          }
                        cors:
                          allow_origin_string_match:
                            - prefix: "*"
                          allow_methods: GET, PUT, DELETE, POST, OPTIONS
                          allow_headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout
                          max_age: "1728000"
                          expose_headers: custom-header-1,grpc-status,grpc-message
                  http_filters:
                    - name: envoy.filters.http.cors
                      typed_config:
                        "@type": type.googleapis.com/envoy.extensions.filters.http.cors.v3.Cors
                    - name: envoy.filters.http.grpc_web
                      typed_config:
                        "@type": type.googleapis.com/envoy.extensions.filters.http.grpc_web.v3.GrpcWeb
                    - name: envoy.filters.http.health_check
                      typed_config:
                        "@type": type.googleapis.com/envoy.extensions.filters.http.health_check.v3.HealthCheck
                        pass_through_mode: false
                        headers:
                        - name: ":path"
                          exact_match: "/healthz"
                        - name: "x-envoy-livenessprobe"
                          exact_match: "healthz"
                    - name: envoy.filters.http.router
                      typed_config:
                        "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
                    
              transport_socket:
                  name: envoy.transport_sockets.tls
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
                    require_client_certificate: false
                    common_tls_context:
                      tls_certificates:
                      - certificate_chain:
                          filename: /etc/ssl/envoy/tls.crt
                        private_key:
                          filename: /etc/ssl/envoy/tls.key
                      alpn_protocols: [ "h2,http/1.1" ]
      clusters:
        - name: envoy_service
          connect_timeout: 0.50s
          type: strict_dns
          http2_protocol_options: {}
          lb_policy: round_robin
          load_assignment:
            cluster_name: envoy_service
            endpoints:
              - lb_endpoints:
                - endpoint:
                    address:
                      socket_address:
                        address: app-server-headless
                        port_value: 8000
          health_checks:
            timeout: 1s
            interval: 10s
            unhealthy_threshold: 2
            healthy_threshold: 2
            grpc_health_check: {}

Now when I make a call. to the server, I get following error from GCP LoadBalancer

```
jsonPayload: {
**statusDetails: "backend_connection_closed_before_data_sent_to_client"**
remoteIp: "49.49.199.6"
@type: "type.googleapis.com/google.cloud.loadbalancing.type.LoadBalancerLogEntry"}
```
Any idea how to resolve this ??
