### ISSUE TITLE
CallCredentials::createFromPlugin does not preserve object for class methods

### ISSUE THREAD

**Issue by TPXP** [grpc/grpc#38760]
### What version of gRPC and what language are you using?
```
# php -i | grep grpc
grpc
grpc support => enabled
grpc module version => 1.64.1
grpc.enable_fork_support => 0 => 0
grpc.grpc_trace => no value => no value
grpc.grpc_verbosity => no value => no value
grpc.log_filename => no value => no value
grpc.poll_strategy => no value => no value
# php -v
PHP 8.3.15 (cli) (built: Dec 20 2024 20:11:30) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.3.15, Copyright (c) Zend Technologies
    with Zend OPcache v8.3.15, Copyright (c), by Zend Technologies
```

### What operating system (Linux, Windows,...) and version?
Linux, in a docker container (Alpine 3.20). PHP and grpc are installed with the distribution packages `php83` and `php83-pecl-grpc`.

### What runtime / compiler are you using (e.g. python version or version of gcc)
PHP 8.3

### What did you do?
We are trying to get our GRPC client to communicate with a TLS server requiring HTTP Basic authentication. So we want to set a `Authorization` metadata field on all requests from this client.

As we are working with a framework, we cannot define functions globally, so we setup a few classes and pass arguments.
```php
class GrpcAuthProvider {
  private $auth_header;
  public function __construct($user, $pass) {
    $this->auth_header = 'Basic '. base64_encode($user':'.$pass);
  }
  public function provideMetadata($context) {
    return ['authorization' => [$this->auth_header]];
  }
}
``` 

```php
$credentials = \Grpc\ChannelCredentials::createSsl();
$auth_provider = new GrpcAuthProvider('username', 'password'); // Assume this is defined dynamically
$credentials = \Grpc\ChannelCredentials::createComposite(
    $credentials,
    \Grpc\CallCredentials::createFromPlugin([$auth_provider, 'provideMetadata'])
);
$channel = new \Grpc\Channel($host, ['credentials' => $credentials]);
```

### What did you expect to see?
A successful authenticated gRPC call going to my server

### What did you see instead?
An error message about `$this` not being what I expected it to be
```
{"message":"Undefined property: Google\\Protobuf\\Descriptor::$auth_header","context":{"userId":"....","exception" {"class":"ErrorException","message":"Undefined property: Google\\Protobuf\\Descriptor::$auth_header","code":0,"file":"/app/Utils/GrpcAuthProvider.php:25"}},"level":400,"level_name":"ERROR","channel":"production","datetime":"2025-02-17T10:07:55.380366+00:00"}
```

I initially suspected PHP's garbage collector to be clearing my object, so I tried to set my object as a member of a static class variable, to no avail (object was just another class).

I also tried to pass other forms of a callable, with the `__invoke` magic method.
```php
class GrpcAuthProvider {
  private $auth_header;
  public function __construct($user, $pass) {
    $this->auth_header = 'Basic '. base64_encode($user':'.$pass)
  }
  public function __invoke($context) {
    return ['authorization' => [$this->auth_header]];
  }
}
```
with `\Grpc\CallCredentials::createFromPlugin($auth_provider)`: gives
```
{"message":"gRPC request","context":{"service":"redacted","duration_ms":6.744902,"method":"/redacted","details":"Getting metadata from plugin failed with error: ","code":14},"level":400,"level_name":"ERROR","channel":"production","datetime":"2025-02-17T12:17:53.321271+00:00","extra":{}
```

We also experimented with a closure (which would be simplest)
```php
$credentials = \Grpc\ChannelCredentials::createSsl();
$username = 'username';
$password = 'password';
$credentials = \Grpc\ChannelCredentials::createComposite(
    $credentials,
    \Grpc\CallCredentials::createFromPlugin(function($context) use ($username, $password) {
      return ['authorization' => ['Basic '. base64_encode($username':'.$password)]];
    })
);
$channel = new \Grpc\Channel($host, ['credentials' => $credentials]);
```
That crashed the PHP runtime (at `zend_call_function`).

A workaround we found is to hack an anonymous class and set our attribute as a `static` member. However that is not pretty
```php
$credentials = \Grpc\ChannelCredentials::createSsl();
$username = 'username';
$password = 'password';

$credentials = (new class($username, $password)
{
  public static string $auth_header;

  public function __construct(string $user, string $password)
  {
    self::$auth_header = 'Basic '.base64_encode($user.':'.$password);
  }

  public static function provideBasicAuthMetadata(mixed $context): array
  {
    return [
      'authorization' => [self::$auth_header],
    ];
  }

  public function createComposite(\Grpc\ChannelCredentials $credentials)
  {
    return \Grpc\ChannelCredentials::createComposite(
      $credentials,
      \Grpc\CallCredentials::createFromPlugin([$this, 'provideBasicAuthMetadata'])
    );
  }
})->createComposite($credentials);
$channel = new \Grpc\Channel($host, ['credentials' => $credentials]);
```

### Anything else we should know about your project / environment?
The target gRPC server is behind a kubernetes nginx ingress - that's how we setup basic authentication.
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/auth-realm: Authentication Required - Example
    nginx.ingress.kubernetes.io/auth-secret: ingress-auth
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/backend-protocol: GRPC
  labels:
    name: example-grpc
  name: example-grpc
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: grpc.example.org
    http:
      paths:
      - backend:
          service:
            name: example
            port:
              name: grpc
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - grpc.example.org
    secretName: grpc.example.org
```
