### ISSUE TITLE
compressed responses not supported by node clients, although advertised (via grpc-accept-encoding) otherwise

### ISSUE THREAD

**Issue by tbak** [grpc/grpc#5355]
I am running a server with GRPC/Java endpoint, and enabled response compression.
When I use GRPC Java client everything works fine. However with node client it
fails in method commons.js#deserialize with:

``` json
 { [Error] code: 13, metadata: undefined }
```

I can see on the server side that node client sends:

```
grpc-accept-encoding: identity,deflate,gzip
```

but appearently the compression is not supprted. When compression is completely
turned off on the server side, everything works fine.

On server side I am running grpc-java 0.13.0, and node version is 0.13.0-pre1.

**Comment by murgatroid99** [comment]
@dgquintas Is this expected behavior? The core seems to send the `grpc-accept-encoding` header by default. If the client does no other compression setup, is it expected to still be able to receive compressed payloads?

**Comment by dgquintas** [comment]
Yes, the client must be able to accept *incoming* messages compressed with any of the methods it advertises in `grpc-accept-encoding`, which is just information the client discloses. In this case it seems the problem lays with the server being confused by this. @carl-mastrangelo ?

**Comment by carl-mastrangelo** [comment]
IIRC The Java server will only compress if setMessageCompression(true) is called on the ServerCall.  

@tbak: Can you see the headers sent back to the client from the server?

**Comment by tbak** [comment]
@carl-mastrangelo If I remember correctly the headers were sent from server to client. If not, it would not work with Java client, which was perfectly fine.

**Comment by carl-mastrangelo** [comment]
@tbak Right, but what were the actual values?  `grpc-accept-encoding` is usually only sent by the client, not the server.  The server sends `grpc-message-encoding`.  That's the value that is important to know.

**Comment by tbak** [comment]
@carl-mastrangelo Here is the wireshark capture of the request/response:
```
Request:
        Header: :scheme: http
        Header: :method: POST
        Header: :path: /abc
        Header: :authority: localhost:8980
        Header: grpc-encoding: identity
        Header: grpc-accept-encoding: identity,deflate,gzip
        Header: te: trailers
        Header: content-type: application/grpc
        Header: user-agent: grpc-node/0.13.0-pre1 grpc-c/0.13.0-pre1 (osx)

Reply:
        Header: :status: 200
        Header: grpc-encoding: gzip
        Header: grpc-accept-encoding: gzip
        Header: content-type: application/grpc
```
The request is sent by nodejs client, while the server is implemented in Java.

The result is:
```
Error is:  { [Error] code: 13, metadata: undefined }
```
